export const GET_ALL_COURSE_REQUEST = "GET_ALL_COURSE_REQUEST"
export const GET_ALL_COURSE_FAILURE = "GET_ALL_COURSE_FAILURE"
export const GET_ALL_COURSE_SUCCESS = "GET_ALL_COURSE_SUCCESS"

export const GET_ALL_TOPIC_REQUEST = "GET_ALL_TOPIC_REQUEST"
export const GET_ALL_TOPIC_FAILURE = "GET_ALL_TOPIC_FAILURE"
export const GET_ALL_TOPIC_SUCCESS = "GET_ALL_TOPIC_SUCCESS"